sudo rm *.dtbo
sudo rm *.mod
sudo rm *.mod.*
sudo rm modules.order
sudo rm Module.symvers
sudo rm *.ko
sudo rm ./inno_mipi_ov9281/*.ko
sudo rm ./inno_mipi_ov9281/*.mod
sudo rm ./inno_mipi_ov9281/*.mod.*
